name: Auto Increment and Push to JitPack

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Set up Gradle
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.9

    # Step 4: Configure Git
    - name: Configure Git
      run: |
        git config user.name "Mahmoud"
        git config user.email "mahmoudkamal4673@gmail.com"

    # Step 5: Determine Next Version
    - name: Get Latest Tag and Increment Version
      id: versioning
      run: |
        # Get the latest tag
        LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) || echo "v0.0.0")
        echo "Latest tag: $LATEST_TAG"

        # Extract major, minor, and patch versions
        VERSION=${LATEST_TAG#v}
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

        # Increment the patch version
        PATCH=$((PATCH + 1))
        NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
        echo "New version: $NEW_VERSION"

        # Export the new version
        echo "version=$NEW_VERSION" >> $GITHUB_ENV

    # Step 6: Create and Push Git Tag
    - name: Create and Push Tag
      run: |
        git tag -a ${{ env.version }} -m "Release ${{ env.version }}"
        git push origin ${{ env.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 7: Create GitHub Release
    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.version }}
        release_name: "Release ${{ env.version }}"
        body: "This is an automatic release for version ${{ env.version }}."
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 8: Trigger Build on JitPack
    - name: Trigger Build on JitPack
      run: |
        echo "Build triggered for tag: ${{ env.version }}"
