name: Trigger Build on Commit and Use Last Tag

on:
  push: # Trigger on every push to any branch
    branches:
      - 'master'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Set up Gradle
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.9

    # Step 4: Configure Git
    - name: Configure Git
      run: |
        git config user.name "Mahmoud"
        git config user.email "mahmoudkamal4673@gmail.com"

    # Step 5: Get the Last Tag
    - name: Get Last Tag
      id: get_last_tag
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
        echo "Last tag: $LAST_TAG"
        echo "last_tag=$LAST_TAG" >> $GITHUB_ENV

    # Step 6: Create GitHub Release (Optional)
    - name: Create GitHub Release
      if: startsWith(env.last_tag, 'v')
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.last_tag }}
        release_name: "Release ${{ env.last_tag }}"
        body: "This is an automatic release for the last tag: ${{ env.last_tag }}."
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 7: Trigger Build on JitPack (or other build step)
    - name: Trigger Build
      run: |
        echo "Build triggered using last tag: ${{ env.last_tag }}"
