name: Push to JitPack

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Set up Gradle
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.9

    # Build and publish to Maven Local (for verification)
    - name: Build and Publish Locally
      run: ./gradlew clean publishToMavenLocal

    # Create a Git Tag for Release
    - name: Create Git Tag
      id: create_tag
      run: |
        VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')
        echo "Version: $VERSION"
        echo "::set-output name=version::$VERSION"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Push the tag to the repository
    - name: Push Tag to GitHub
      run: |
        git tag -a v${{ steps.create_tag.outputs.version }} -m "Release v${{ steps.create_tag.outputs.version }}"
        git push origin v${{ steps.create_tag.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Trigger Build on JitPack
    - name: Trigger Build on JitPack
      run: |
        echo "Build triggered for tag: v${{ steps.create_tag.outputs.version }}"
