name: Trigger Build on Tag Push

on:
  push:
    tags:
      - '**' # Trigger on all tag pushes

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Set up Gradle
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.9

    # Step 4: Configure Git
    - name: Configure Git
      run: |
        git config user.name "Mahmoud"
        git config user.email "mahmoudkamal4673@gmail.com"

    # Step 5: Extract Tag Name
    - name: Get Tag Name
      id: get_tag
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        echo "Tag Name: $TAG_NAME"
        echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

    # Step 6: Create GitHub Release
    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.tag_name }}
        release_name: "Release ${{ env.tag_name }}"
        body: "This is an automatic release for the tag: ${{ env.tag_name }}."
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 7: Trigger Build on JitPack (or other build step)
    - name: Trigger Build
      run: |
        echo "Build triggered using tag: ${{ env.tag_name }}"
