name: Push to JitPack

on:
  push:
    branches:
      - master # Trigger on pushes to the master branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Set up Gradle
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.9

    # Step 4: Configure Git
    - name: Configure Git
      run: |
        git config user.name "Mahmoud"
        git config user.email "mahmoudkamal4673@gmail.com"

    # Step 5: Build and Publish Locally
    - name: Build and Publish Locally
      run: ./gradlew clean publishToMavenLocal

    # Step 6: Extract Version from Gradle
    - name: Extract Version
      id: extract_version
      run: |
        VERSION=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')
        echo "Version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV

    # Step 7: Create and Push Git Tag
    - name: Create and Push Tag
      run: |
        git tag -a v${{ env.version }} -m "Release v${{ env.version }}"
        git push origin v${{ env.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 8: Create GitHub Release
    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ env.version }}
        release_name: "Release v${{ env.version }}"
        body: "This is an automatic release for version v${{ env.version }}."
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 9: Trigger Build on JitPack
    - name: Trigger Build on JitPack
      run: |
        echo "Build triggered for tag: v${{ env.version }}"
