name: Trigger Build on Manual Tagging

on:
  push:
    tags:
      - 'v*' # Trigger only when a tag starting with 'v' is pushed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Set up Gradle
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.9

    # Step 4: Configure Git
    - name: Configure Git
      run: |
        git config user.name "Mahmoud"
        git config user.email "mahmoudkamal4673@gmail.com"

    # Step 5: Get the Current Tag
    - name: Get Current Tag
      id: get_tag
      run: |
        CURRENT_TAG=$(git tag --points-at HEAD)
        if [ -z "$CURRENT_TAG" ]; then
          echo "No tag found for this commit."
          exit 1
        fi
        echo "Current tag: $CURRENT_TAG"
        echo "tag=$CURRENT_TAG" >> $GITHUB_ENV

    # Step 6: Create GitHub Release
    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.tag }}
        release_name: "Release ${{ env.tag }}"
        body: "This is an automatic release for version ${{ env.tag }}."
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 7: Trigger Build on JitPack
    - name: Trigger Build on JitPack
      run: |
        echo "Build triggered for tag: ${{ env.tag }}"
