name: Automatic Build and Push to JitPack

on:
  push:
    branches:
      - master # Trigger the workflow on every push to the master branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Set up Gradle
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.9

    # Step 4: Configure Git
    - name: Configure Git
      run: |
        git config user.name "Mahmoud"
        git config user.email "mahmoudkamal4673@gmail.com"

    # Step 5: Create a Lightweight Tag and Push
    - name: Create and Push Lightweight Tag
      run: |
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        TAG_NAME="auto-build-${TIMESTAMP}"
        git tag -a "$TAG_NAME" -m "Automatic build tag $TAG_NAME"
        git push origin "$TAG_NAME"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 6: Trigger Build on JitPack
    - name: Trigger Build on JitPack
      run: |
        echo "Build triggered for the latest commit on the master branch"
